const $ = (id) => document.getElementById(id);
const form = $('audit-form');
let latestResult = null;

const lines = (value) => value.split('\n').map((item) => item.trim()).filter(Boolean);
const event = (name, details = {}) => fetch('/api/events', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event:name,details})}).catch(()=>{});

function payload(){return{platform:$('platform').value,title:$('title').value.trim(),description:$('description').value.trim(),price:Number($('price').value),product_type:$('product-type').value.trim(),audience:$('audience').value.trim(),deliverables:lines($('deliverables').value),preview_assets:lines($('previews').value),refund_policy:$('refund-policy').value.trim(),support_text:$('support-text').value.trim(),claims:lines($('claims').value)}}
function group(title,items,kind){if(!items.length)return'';return `<section class="result-group ${kind}"><header><h3>${title}</h3><span class="count">${items.length}</span></header><ul>${items.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></section>`}
function escapeHtml(value){const e=document.createElement('div');e.textContent=value;return e.innerHTML}
function copyFor(decision){return decision==='launch'?'No launch blockers found. Complete the platform checklist before publishing.':decision==='quarantine'?'Blocking risk detected. Do not publish until it is removed or substantiated.':'The core offer is workable, but the listing needs another editing pass.'}

function render(result){latestResult=result;$('empty-state').hidden=true;$('result-state').hidden=false;$('score').textContent=result.readiness_score;$('decision').textContent=result.decision[0].toUpperCase()+result.decision.slice(1);$('decision-copy').textContent=copyFor(result.decision);$('score-ring').style.background=`conic-gradient(${result.decision==='quarantine'?'var(--red)':result.decision==='revise'?'var(--amber)':'var(--green)'} ${result.readiness_score*3.6}deg,#e2e7e4 0deg)`;$('checks-passed').textContent=`${result.checks_passed} of ${result.checks_total} checks passed`;$('ruleset').textContent=`Ruleset ${result.ruleset_version}`;$('blocker-count').textContent=result.blocking_issues.length;$('warning-count').textContent=result.warnings.length;$('missing-count').textContent=result.missing_assets.length;$('platform-name').textContent=$('platform').value;$('platform-checklist').innerHTML=result.platform_checklist.map(x=>`<li>${escapeHtml(x)}</li>`).join('');$('result-groups').innerHTML=group('Launch blockers',result.blocking_issues,'blocking')+group('Warnings',result.warnings,'warning')+group('Missing assets',result.missing_assets,'info')+group('Recommended edits',result.recommendations,'good')+group('Compliance notes',result.compliance_flags,'info');window.scrollTo({top:0,behavior:'smooth'})}

form.addEventListener('submit',async(e)=>{e.preventDefault();$('form-error').textContent='';const button=form.querySelector('button[type="submit"]');button.disabled=true;button.querySelector('span').textContent='Auditing…';try{const response=await fetch('/api/audit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});const data=await response.json();if(!response.ok)throw new Error(data.error||'Audit failed.');render(data)}catch(error){$('form-error').textContent=error.message}finally{button.disabled=false;button.querySelector('span').textContent='Run launch audit'}});
$('description').addEventListener('input',()=>{$('word-count').textContent=`${$('description').value.trim().split(/\s+/).filter(Boolean).length} words`});
$('load-sample').addEventListener('click',()=>{const sample={platform:'Fourthwall',type:'Resource bundle',price:'39',title:'AI Creator Workflow Bundle',audience:'Creators and independent service providers',description:'A three-product digital resource bundle for creators and independent service providers building practical AI-assisted workflows. It includes client intake and automation mapping templates, podcast repurposing workflows, and micro-course production checklists. Files are provided for personal or internal business use. No income promises; results depend on your market, offer, and execution.',deliverables:'Client intake workflow kit (ZIP)\nPodcast repurposing workflow kit (ZIP)\nMicro-course production kit (ZIP)',previews:'Square product cover\nInterior workflow preview',refund:'Because this is a digital download, refund requests are reviewed individually when a file is defective or materially different from the listing.',support:'Use the storefront contact form for product support. Replies are normally sent within two business days.',claims:''};$('platform').value=sample.platform;$('product-type').value=sample.type;$('price').value=sample.price;$('title').value=sample.title;$('audience').value=sample.audience;$('description').value=sample.description;$('deliverables').value=sample.deliverables;$('previews').value=sample.previews;$('refund-policy').value=sample.refund;$('support-text').value=sample.support;$('claims').value=sample.claims;$('description').dispatchEvent(new Event('input'));event('sample_loaded')});
$('run-again').addEventListener('click',()=>{$('audit-heading').scrollIntoView({behavior:'smooth'})});
$('print-report').addEventListener('click',()=>{event('print_report');window.print()});
$('export-csv').addEventListener('click',()=>{if(!latestResult)return;const rows=[['field','value'],...Object.entries(latestResult).flatMap(([key,value])=>Array.isArray(value)?value.map(item=>[key,item]):[[key,value]])];const csv=rows.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));link.download='listing-audit.csv';link.click();URL.revokeObjectURL(link.href);event('export_csv')});
const dialog=$('upgrade-dialog');function openUpgrade(){$('billing-note').textContent='Choose a plan to continue to secure Stripe Checkout.';event('upgrade_clicked',{source:latestResult?'results':'header'});dialog.showModal()}$('upgrade-top').addEventListener('click',openUpgrade);$('upgrade-result').addEventListener('click',openUpgrade);$('close-dialog').addEventListener('click',()=>dialog.close());$('notify-pro').addEventListener('click',()=>dialog.close());
document.querySelectorAll('[data-plan]').forEach(button=>button.addEventListener('click',async()=>{const plan=button.dataset.plan;const original=button.querySelector('small').textContent;button.disabled=true;button.querySelector('small').textContent='Opening checkout...';$('billing-note').textContent='Preparing secure checkout...';try{const response=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Checkout could not be started.');window.location.assign(data.url)}catch(error){$('billing-note').textContent=error.message}finally{button.disabled=false;button.querySelector('small').textContent=original}}));
event('app_opened');

